# Generated by Django 6.0.5 on 2026-06-15 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_chatroom_chatmessage_productimage_reviewimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/'),
        ),
    ]
