# Generated by Django 6.0.5 on 2026-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_reviewimage_options_reviewimage_uploaded_at_and_more'),
    ]

    operations = [
    ]
